spring:  
  application:    
    name: config-server
  cloud:    
    config:      
      server:        
        git:          
          uri: https://github.com/alessiofiore/spring-cloud.git
          cloneOnStart: true
          searchPaths: config
server:
  port: ${PORT:8081}
