spring:  
  application:    
    name: config
  cloud:    
    config:      
      server:        
        git:          
          uri: https://github.com/alessiofiore/spring-cloud.git
          cloneOnStart: true
          searchPaths: config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    
server:
  port: ${PORT:8081}
