spring:  
    application:    
        name: config  
    cloud:    
        config:      
            server:        
                git:          
                    uri: https://github.com/alessiofiore/spring-cloud.git
                    searchPaths: config
server:
    port: ${PORT:8081}
